// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'persistence/entities/funscript.dart';
import 'persistence/entities/key_value.dart';
import 'persistence/entities/media.dart';
import 'persistence/entities/media_list.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6336503572128758716),
    name: 'FunscriptFile',
    lastPropertyId: const obx_int.IdUid(6, 4024860914835720402),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5204507680085067774),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 555857619558970040),
        name: 'path',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 171346948306968217),
        name: 'metadataDb',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6662490761287938469),
        name: 'averageSpeed',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8876777613061484524),
        name: 'averageMin',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4024860914835720402),
        name: 'averageMax',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'media',
        srcEntity: 'Media',
        srcField: 'funscripts',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7258241673948349047),
    name: 'KeyValue',
    lastPropertyId: const obx_int.IdUid(3, 1414269244050387444),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1110636866453135931),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5324733068088730942),
        name: 'key',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 7710736713395324780),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1414269244050387444),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7413207220464161675),
    name: 'Media',
    lastPropertyId: const obx_int.IdUid(7, 8980549126330725608),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2272196324513795759),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8752328575883400114),
        name: 'dbType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2012092204144470782),
        name: 'dbRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1805444033031759801),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7116599105536418738),
        name: 'mediaPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5675724617542944058),
        name: 'duration',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8980549126330725608),
        name: 'playCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 1036988608575817632),
        name: 'funscripts',
        targetId: const obx_int.IdUid(1, 6336503572128758716),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'lists',
        srcEntity: 'MediaList',
        srcField: 'entries',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8423154730704696626),
    name: 'MediaList',
    lastPropertyId: const obx_int.IdUid(4, 2292070019112880722),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4957973923938783710),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2125805251190299749),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 4073660022278031961),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 383115343253487673),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2292070019112880722),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 8426637893943230846),
        name: 'entries',
        targetId: const obx_int.IdUid(3, 7413207220464161675),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 8423154730704696626),
    lastIndexId: const obx_int.IdUid(2, 4073660022278031961),
    lastRelationId: const obx_int.IdUid(2, 8426637893943230846),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FunscriptFile: obx_int.EntityDefinition<FunscriptFile>(
      model: _entities[0],
      toOneRelations: (FunscriptFile object) => [],
      toManyRelations: (FunscriptFile object) => {
        obx_int.RelInfo<Media>.toManyBacklink(1, object.id): object.media,
      },
      getId: (FunscriptFile object) => object.id,
      setId: (FunscriptFile object, int id) {
        object.id = id;
      },
      objectToFB: (FunscriptFile object, fb.Builder fbb) {
        final pathOffset = fbb.writeString(object.path);
        final metadataDbOffset = object.metadataDb == null
            ? null
            : fbb.writeString(object.metadataDb!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, pathOffset);
        fbb.addOffset(2, metadataDbOffset);
        fbb.addFloat64(3, object.averageSpeed);
        fbb.addFloat64(4, object.averageMin);
        fbb.addFloat64(5, object.averageMax);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final pathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final averageSpeedParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final averageMinParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final averageMaxParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object =
            FunscriptFile(
                path: pathParam,
                averageSpeed: averageSpeedParam,
                averageMin: averageMinParam,
                averageMax: averageMaxParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..metadataDb = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 8);
        obx_int.InternalToManyAccess.setRelInfo<FunscriptFile>(
          object.media,
          store,
          obx_int.RelInfo<Media>.toManyBacklink(1, object.id),
        );
        return object;
      },
    ),
    KeyValue: obx_int.EntityDefinition<KeyValue>(
      model: _entities[1],
      toOneRelations: (KeyValue object) => [],
      toManyRelations: (KeyValue object) => {},
      getId: (KeyValue object) => object.id,
      setId: (KeyValue object, int id) {
        object.id = id;
      },
      objectToFB: (KeyValue object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = KeyValue(key: keyParam, value: valueParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Media: obx_int.EntityDefinition<Media>(
      model: _entities[2],
      toOneRelations: (Media object) => [],
      toManyRelations: (Media object) => {
        obx_int.RelInfo<Media>.toMany(1, object.id): object.funscripts,
        obx_int.RelInfo<MediaList>.toManyBacklink(2, object.id): object.lists,
      },
      getId: (Media object) => object.id,
      setId: (Media object, int id) {
        object.id = id;
      },
      objectToFB: (Media object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final mediaPathOffset = fbb.writeString(object.mediaPath);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.dbType);
        fbb.addInt64(2, object.dbRating);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, mediaPathOffset);
        fbb.addFloat64(5, object.duration);
        fbb.addInt64(6, object.playCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final mediaPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final playCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final durationParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final object =
            Media(
                name: nameParam,
                mediaPath: mediaPathParam,
                playCount: playCountParam,
                duration: durationParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..dbType = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                6,
              )
              ..dbRating = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                8,
              );
        obx_int.InternalToManyAccess.setRelInfo<Media>(
          object.funscripts,
          store,
          obx_int.RelInfo<Media>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<Media>(
          object.lists,
          store,
          obx_int.RelInfo<MediaList>.toManyBacklink(2, object.id),
        );
        return object;
      },
    ),
    MediaList: obx_int.EntityDefinition<MediaList>(
      model: _entities[3],
      toOneRelations: (MediaList object) => [],
      toManyRelations: (MediaList object) => {
        obx_int.RelInfo<MediaList>.toMany(2, object.id): object.entries,
      },
      getId: (MediaList object) => object.id,
      setId: (MediaList object, int id) {
        object.id = id;
      },
      objectToFB: (MediaList object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addInt64(3, object.sortOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = MediaList(
          name: nameParam,
          description: descriptionParam,
          sortOrder: sortOrderParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<MediaList>(
          object.entries,
          store,
          obx_int.RelInfo<MediaList>.toMany(2, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FunscriptFile] entity fields to define ObjectBox queries.
class FunscriptFile_ {
  /// See [FunscriptFile.id].
  static final id = obx.QueryIntegerProperty<FunscriptFile>(
    _entities[0].properties[0],
  );

  /// See [FunscriptFile.path].
  static final path = obx.QueryStringProperty<FunscriptFile>(
    _entities[0].properties[1],
  );

  /// See [FunscriptFile.metadataDb].
  static final metadataDb = obx.QueryStringProperty<FunscriptFile>(
    _entities[0].properties[2],
  );

  /// See [FunscriptFile.averageSpeed].
  static final averageSpeed = obx.QueryDoubleProperty<FunscriptFile>(
    _entities[0].properties[3],
  );

  /// See [FunscriptFile.averageMin].
  static final averageMin = obx.QueryDoubleProperty<FunscriptFile>(
    _entities[0].properties[4],
  );

  /// See [FunscriptFile.averageMax].
  static final averageMax = obx.QueryDoubleProperty<FunscriptFile>(
    _entities[0].properties[5],
  );
}

/// [KeyValue] entity fields to define ObjectBox queries.
class KeyValue_ {
  /// See [KeyValue.id].
  static final id = obx.QueryIntegerProperty<KeyValue>(
    _entities[1].properties[0],
  );

  /// See [KeyValue.key].
  static final key = obx.QueryStringProperty<KeyValue>(
    _entities[1].properties[1],
  );

  /// See [KeyValue.value].
  static final value = obx.QueryStringProperty<KeyValue>(
    _entities[1].properties[2],
  );
}

/// [Media] entity fields to define ObjectBox queries.
class Media_ {
  /// See [Media.id].
  static final id = obx.QueryIntegerProperty<Media>(_entities[2].properties[0]);

  /// See [Media.dbType].
  static final dbType = obx.QueryIntegerProperty<Media>(
    _entities[2].properties[1],
  );

  /// See [Media.dbRating].
  static final dbRating = obx.QueryIntegerProperty<Media>(
    _entities[2].properties[2],
  );

  /// See [Media.name].
  static final name = obx.QueryStringProperty<Media>(
    _entities[2].properties[3],
  );

  /// See [Media.mediaPath].
  static final mediaPath = obx.QueryStringProperty<Media>(
    _entities[2].properties[4],
  );

  /// See [Media.duration].
  static final duration = obx.QueryDoubleProperty<Media>(
    _entities[2].properties[5],
  );

  /// See [Media.playCount].
  static final playCount = obx.QueryIntegerProperty<Media>(
    _entities[2].properties[6],
  );

  /// see [Media.funscripts]
  static final funscripts = obx.QueryRelationToMany<Media, FunscriptFile>(
    _entities[2].relations[0],
  );
}

/// [MediaList] entity fields to define ObjectBox queries.
class MediaList_ {
  /// See [MediaList.id].
  static final id = obx.QueryIntegerProperty<MediaList>(
    _entities[3].properties[0],
  );

  /// See [MediaList.name].
  static final name = obx.QueryStringProperty<MediaList>(
    _entities[3].properties[1],
  );

  /// See [MediaList.description].
  static final description = obx.QueryStringProperty<MediaList>(
    _entities[3].properties[2],
  );

  /// See [MediaList.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<MediaList>(
    _entities[3].properties[3],
  );

  /// see [MediaList.entries]
  static final entries = obx.QueryRelationToMany<MediaList, Media>(
    _entities[3].relations[0],
  );
}
