// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'persistence/entities/funscript_file.dart';
import 'persistence/entities/key_value.dart';
import 'persistence/entities/media_file.dart';
import 'persistence/entities/media_metadata.dart';
import 'persistence/entities/user_category.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6721894957622329438),
    name: 'FunscriptFile',
    lastPropertyId: const obx_int.IdUid(9, 7117044257309832574),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5344860597020906881),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6369810481837526684),
        name: 'path',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2122774965455246393),
        name: 'metadataDb',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4404486450253767010),
        name: 'funscriptHash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8562337990343238772),
        name: 'averageSpeed',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2035956539130872600),
        name: 'averageMin',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6378628159952366043),
        name: 'averageMax',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 503151519764925209),
        name: 'isScriptToken',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7117044257309832574),
        name: 'fileNotFound',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'media',
        srcEntity: 'MediaFile',
        srcField: 'funscripts',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7674550725051663938),
    name: 'KeyValue',
    lastPropertyId: const obx_int.IdUid(3, 9082959352345638832),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3219829787470920094),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8279721603043076064),
        name: 'key',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 6206695141068141028),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9082959352345638832),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 9071081501648173308),
    name: 'MediaFile',
    lastPropertyId: const obx_int.IdUid(11, 7639782100621504112),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2459842670283849194),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7163213913672456924),
        name: 'dbType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9102323203500349783),
        name: 'dbRating',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4772981549358255707),
        name: 'fileHash',
        type: 9,
        flags: 40,
        indexId: const obx_int.IdUid(2, 4897266285626196375),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3544771685604182159),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 662721477061299319),
        name: 'dbAliases',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4663251282778927414),
        name: 'mediaPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5350016031430485967),
        name: 'playCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 532169928426936197),
        name: 'fileNotFound',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4507288092959833377),
        name: 'metadataId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 4663592735602559600),
        relationField: 'metadata',
        relationTarget: 'MediaMetadata',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7639782100621504112),
        name: 'mainFunscriptId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 1808176005500392495),
        relationField: 'mainFunscript',
        relationTarget: 'FunscriptFile',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 4369759362702757159),
        name: 'funscripts',
        targetId: const obx_int.IdUid(1, 6721894957622329438),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'categories',
        srcEntity: 'UserCategory',
        srcField: 'entries',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3798506222748057429),
    name: 'MediaMetadata',
    lastPropertyId: const obx_int.IdUid(13, 6350099887193462324),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1251389638291966319),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6217182915302439762),
        name: 'duration',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7104058348882122449),
        name: 'width',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6528590328858852699),
        name: 'height',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6490084546095589020),
        name: 'videoCodec',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5583060834586545550),
        name: 'audioCodec',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6976266162093139583),
        name: 'bitRate',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1426896271963727519),
        name: 'rotation',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1198793567372423600),
        name: 'frameRate',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7194026950691526660),
        name: 'audioChannels',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5549035287497801629),
        name: 'pixelFormat',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6347364791147014947),
        name: 'aspectRatio',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6350099887193462324),
        name: 'creationTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1260086361330587750),
    name: 'UserCategory',
    lastPropertyId: const obx_int.IdUid(4, 8595775567884591280),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4054058505120431548),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5437909343206654273),
        name: 'name',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 6057485892732913392),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 980155483226409642),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8595775567884591280),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 7266238481079671849),
        name: 'entries',
        targetId: const obx_int.IdUid(3, 9071081501648173308),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 1260086361330587750),
    lastIndexId: const obx_int.IdUid(5, 6057485892732913392),
    lastRelationId: const obx_int.IdUid(2, 7266238481079671849),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    FunscriptFile: obx_int.EntityDefinition<FunscriptFile>(
      model: _entities[0],
      toOneRelations: (FunscriptFile object) => [],
      toManyRelations: (FunscriptFile object) => {
        obx_int.RelInfo<MediaFile>.toManyBacklink(1, object.id): object.media,
      },
      getId: (FunscriptFile object) => object.id,
      setId: (FunscriptFile object, int id) {
        object.id = id;
      },
      objectToFB: (FunscriptFile object, fb.Builder fbb) {
        final pathOffset = fbb.writeString(object.path);
        final metadataDbOffset = object.metadataDb == null
            ? null
            : fbb.writeString(object.metadataDb!);
        final funscriptHashOffset = object.funscriptHash == null
            ? null
            : fbb.writeString(object.funscriptHash!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, pathOffset);
        fbb.addOffset(2, metadataDbOffset);
        fbb.addOffset(3, funscriptHashOffset);
        fbb.addFloat64(4, object.averageSpeed);
        fbb.addFloat64(5, object.averageMin);
        fbb.addFloat64(6, object.averageMax);
        fbb.addBool(7, object.isScriptToken);
        fbb.addBool(8, object.fileNotFound);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final pathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final averageSpeedParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final averageMinParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final averageMaxParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final isScriptTokenParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          18,
          false,
        );
        final fileNotFoundParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final funscriptHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object =
            FunscriptFile(
                path: pathParam,
                averageSpeed: averageSpeedParam,
                averageMin: averageMinParam,
                averageMax: averageMaxParam,
                isScriptToken: isScriptTokenParam,
                fileNotFound: fileNotFoundParam,
                funscriptHash: funscriptHashParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..metadataDb = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGetNullable(buffer, rootOffset, 8);
        obx_int.InternalToManyAccess.setRelInfo<FunscriptFile>(
          object.media,
          store,
          obx_int.RelInfo<MediaFile>.toManyBacklink(1, object.id),
        );
        return object;
      },
    ),
    KeyValue: obx_int.EntityDefinition<KeyValue>(
      model: _entities[1],
      toOneRelations: (KeyValue object) => [],
      toManyRelations: (KeyValue object) => {},
      getId: (KeyValue object) => object.id,
      setId: (KeyValue object, int id) {
        object.id = id;
      },
      objectToFB: (KeyValue object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = KeyValue(key: keyParam, value: valueParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    MediaFile: obx_int.EntityDefinition<MediaFile>(
      model: _entities[2],
      toOneRelations: (MediaFile object) => [
        object.metadata,
        object.mainFunscript,
      ],
      toManyRelations: (MediaFile object) => {
        obx_int.RelInfo<MediaFile>.toMany(1, object.id): object.funscripts,
        obx_int.RelInfo<UserCategory>.toManyBacklink(2, object.id):
            object.categories,
      },
      getId: (MediaFile object) => object.id,
      setId: (MediaFile object, int id) {
        object.id = id;
      },
      objectToFB: (MediaFile object, fb.Builder fbb) {
        final fileHashOffset = object.fileHash == null
            ? null
            : fbb.writeString(object.fileHash!);
        final nameOffset = fbb.writeString(object.name);
        final dbAliasesOffset = fbb.writeString(object.dbAliases);
        final mediaPathOffset = fbb.writeString(object.mediaPath);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.dbType);
        fbb.addInt64(2, object.dbRating);
        fbb.addOffset(3, fileHashOffset);
        fbb.addOffset(4, nameOffset);
        fbb.addOffset(5, dbAliasesOffset);
        fbb.addOffset(6, mediaPathOffset);
        fbb.addInt64(7, object.playCount);
        fbb.addBool(8, object.fileNotFound);
        fbb.addInt64(9, object.metadata.targetId);
        fbb.addInt64(10, object.mainFunscript.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final mediaPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final fileHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final playCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final fileNotFoundParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          20,
          false,
        );
        final object =
            MediaFile(
                name: nameParam,
                mediaPath: mediaPathParam,
                fileHash: fileHashParam,
                playCount: playCountParam,
                fileNotFound: fileNotFoundParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..dbType = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                6,
              )
              ..dbRating = const fb.Int64Reader().vTableGetNullable(
                buffer,
                rootOffset,
                8,
              )
              ..dbAliases = const fb.StringReader(
                asciiOptimization: true,
              ).vTableGet(buffer, rootOffset, 14, '');
        object.metadata.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        object.metadata.attach(store);
        object.mainFunscript.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.mainFunscript.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<MediaFile>(
          object.funscripts,
          store,
          obx_int.RelInfo<MediaFile>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<MediaFile>(
          object.categories,
          store,
          obx_int.RelInfo<UserCategory>.toManyBacklink(2, object.id),
        );
        return object;
      },
    ),
    MediaMetadata: obx_int.EntityDefinition<MediaMetadata>(
      model: _entities[3],
      toOneRelations: (MediaMetadata object) => [],
      toManyRelations: (MediaMetadata object) => {},
      getId: (MediaMetadata object) => object.id,
      setId: (MediaMetadata object, int id) {
        object.id = id;
      },
      objectToFB: (MediaMetadata object, fb.Builder fbb) {
        final videoCodecOffset = object.videoCodec == null
            ? null
            : fbb.writeString(object.videoCodec!);
        final audioCodecOffset = object.audioCodec == null
            ? null
            : fbb.writeString(object.audioCodec!);
        final pixelFormatOffset = object.pixelFormat == null
            ? null
            : fbb.writeString(object.pixelFormat!);
        final aspectRatioOffset = object.aspectRatio == null
            ? null
            : fbb.writeString(object.aspectRatio!);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.duration);
        fbb.addInt64(2, object.width);
        fbb.addInt64(3, object.height);
        fbb.addOffset(4, videoCodecOffset);
        fbb.addOffset(5, audioCodecOffset);
        fbb.addInt64(6, object.bitRate);
        fbb.addInt64(7, object.rotation);
        fbb.addFloat64(8, object.frameRate);
        fbb.addInt64(9, object.audioChannels);
        fbb.addOffset(10, pixelFormatOffset);
        fbb.addOffset(11, aspectRatioOffset);
        fbb.addInt64(12, object.creationTime?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final creationTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final durationParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final widthParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final heightParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          10,
        );
        final videoCodecParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final audioCodecParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final bitRateParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final rotationParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final frameRateParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final audioChannelsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final pixelFormatParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final aspectRatioParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final creationTimeParam = creationTimeValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                creationTimeValue,
                isUtc: true,
              );
        final object = MediaMetadata(
          duration: durationParam,
          width: widthParam,
          height: heightParam,
          videoCodec: videoCodecParam,
          audioCodec: audioCodecParam,
          bitRate: bitRateParam,
          rotation: rotationParam,
          frameRate: frameRateParam,
          audioChannels: audioChannelsParam,
          pixelFormat: pixelFormatParam,
          aspectRatio: aspectRatioParam,
          creationTime: creationTimeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    UserCategory: obx_int.EntityDefinition<UserCategory>(
      model: _entities[4],
      toOneRelations: (UserCategory object) => [],
      toManyRelations: (UserCategory object) => {
        obx_int.RelInfo<UserCategory>.toMany(2, object.id): object.entries,
      },
      getId: (UserCategory object) => object.id,
      setId: (UserCategory object, int id) {
        object.id = id;
      },
      objectToFB: (UserCategory object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addInt64(3, object.sortOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = UserCategory(
          name: nameParam,
          description: descriptionParam,
          sortOrder: sortOrderParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<UserCategory>(
          object.entries,
          store,
          obx_int.RelInfo<UserCategory>.toMany(2, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [FunscriptFile] entity fields to define ObjectBox queries.
class FunscriptFile_ {
  /// See [FunscriptFile.id].
  static final id = obx.QueryIntegerProperty<FunscriptFile>(
    _entities[0].properties[0],
  );

  /// See [FunscriptFile.path].
  static final path = obx.QueryStringProperty<FunscriptFile>(
    _entities[0].properties[1],
  );

  /// See [FunscriptFile.metadataDb].
  static final metadataDb = obx.QueryStringProperty<FunscriptFile>(
    _entities[0].properties[2],
  );

  /// See [FunscriptFile.funscriptHash].
  static final funscriptHash = obx.QueryStringProperty<FunscriptFile>(
    _entities[0].properties[3],
  );

  /// See [FunscriptFile.averageSpeed].
  static final averageSpeed = obx.QueryDoubleProperty<FunscriptFile>(
    _entities[0].properties[4],
  );

  /// See [FunscriptFile.averageMin].
  static final averageMin = obx.QueryDoubleProperty<FunscriptFile>(
    _entities[0].properties[5],
  );

  /// See [FunscriptFile.averageMax].
  static final averageMax = obx.QueryDoubleProperty<FunscriptFile>(
    _entities[0].properties[6],
  );

  /// See [FunscriptFile.isScriptToken].
  static final isScriptToken = obx.QueryBooleanProperty<FunscriptFile>(
    _entities[0].properties[7],
  );

  /// See [FunscriptFile.fileNotFound].
  static final fileNotFound = obx.QueryBooleanProperty<FunscriptFile>(
    _entities[0].properties[8],
  );
}

/// [KeyValue] entity fields to define ObjectBox queries.
class KeyValue_ {
  /// See [KeyValue.id].
  static final id = obx.QueryIntegerProperty<KeyValue>(
    _entities[1].properties[0],
  );

  /// See [KeyValue.key].
  static final key = obx.QueryStringProperty<KeyValue>(
    _entities[1].properties[1],
  );

  /// See [KeyValue.value].
  static final value = obx.QueryStringProperty<KeyValue>(
    _entities[1].properties[2],
  );
}

/// [MediaFile] entity fields to define ObjectBox queries.
class MediaFile_ {
  /// See [MediaFile.id].
  static final id = obx.QueryIntegerProperty<MediaFile>(
    _entities[2].properties[0],
  );

  /// See [MediaFile.dbType].
  static final dbType = obx.QueryIntegerProperty<MediaFile>(
    _entities[2].properties[1],
  );

  /// See [MediaFile.dbRating].
  static final dbRating = obx.QueryIntegerProperty<MediaFile>(
    _entities[2].properties[2],
  );

  /// See [MediaFile.fileHash].
  static final fileHash = obx.QueryStringProperty<MediaFile>(
    _entities[2].properties[3],
  );

  /// See [MediaFile.name].
  static final name = obx.QueryStringProperty<MediaFile>(
    _entities[2].properties[4],
  );

  /// See [MediaFile.dbAliases].
  static final dbAliases = obx.QueryStringProperty<MediaFile>(
    _entities[2].properties[5],
  );

  /// See [MediaFile.mediaPath].
  static final mediaPath = obx.QueryStringProperty<MediaFile>(
    _entities[2].properties[6],
  );

  /// See [MediaFile.playCount].
  static final playCount = obx.QueryIntegerProperty<MediaFile>(
    _entities[2].properties[7],
  );

  /// See [MediaFile.fileNotFound].
  static final fileNotFound = obx.QueryBooleanProperty<MediaFile>(
    _entities[2].properties[8],
  );

  /// See [MediaFile.metadata].
  static final metadata = obx.QueryRelationToOne<MediaFile, MediaMetadata>(
    _entities[2].properties[9],
  );

  /// See [MediaFile.mainFunscript].
  static final mainFunscript = obx.QueryRelationToOne<MediaFile, FunscriptFile>(
    _entities[2].properties[10],
  );

  /// see [MediaFile.funscripts]
  static final funscripts = obx.QueryRelationToMany<MediaFile, FunscriptFile>(
    _entities[2].relations[0],
  );
}

/// [MediaMetadata] entity fields to define ObjectBox queries.
class MediaMetadata_ {
  /// See [MediaMetadata.id].
  static final id = obx.QueryIntegerProperty<MediaMetadata>(
    _entities[3].properties[0],
  );

  /// See [MediaMetadata.duration].
  static final duration = obx.QueryDoubleProperty<MediaMetadata>(
    _entities[3].properties[1],
  );

  /// See [MediaMetadata.width].
  static final width = obx.QueryIntegerProperty<MediaMetadata>(
    _entities[3].properties[2],
  );

  /// See [MediaMetadata.height].
  static final height = obx.QueryIntegerProperty<MediaMetadata>(
    _entities[3].properties[3],
  );

  /// See [MediaMetadata.videoCodec].
  static final videoCodec = obx.QueryStringProperty<MediaMetadata>(
    _entities[3].properties[4],
  );

  /// See [MediaMetadata.audioCodec].
  static final audioCodec = obx.QueryStringProperty<MediaMetadata>(
    _entities[3].properties[5],
  );

  /// See [MediaMetadata.bitRate].
  static final bitRate = obx.QueryIntegerProperty<MediaMetadata>(
    _entities[3].properties[6],
  );

  /// See [MediaMetadata.rotation].
  static final rotation = obx.QueryIntegerProperty<MediaMetadata>(
    _entities[3].properties[7],
  );

  /// See [MediaMetadata.frameRate].
  static final frameRate = obx.QueryDoubleProperty<MediaMetadata>(
    _entities[3].properties[8],
  );

  /// See [MediaMetadata.audioChannels].
  static final audioChannels = obx.QueryIntegerProperty<MediaMetadata>(
    _entities[3].properties[9],
  );

  /// See [MediaMetadata.pixelFormat].
  static final pixelFormat = obx.QueryStringProperty<MediaMetadata>(
    _entities[3].properties[10],
  );

  /// See [MediaMetadata.aspectRatio].
  static final aspectRatio = obx.QueryStringProperty<MediaMetadata>(
    _entities[3].properties[11],
  );

  /// See [MediaMetadata.creationTime].
  static final creationTime = obx.QueryDateProperty<MediaMetadata>(
    _entities[3].properties[12],
  );
}

/// [UserCategory] entity fields to define ObjectBox queries.
class UserCategory_ {
  /// See [UserCategory.id].
  static final id = obx.QueryIntegerProperty<UserCategory>(
    _entities[4].properties[0],
  );

  /// See [UserCategory.name].
  static final name = obx.QueryStringProperty<UserCategory>(
    _entities[4].properties[1],
  );

  /// See [UserCategory.description].
  static final description = obx.QueryStringProperty<UserCategory>(
    _entities[4].properties[2],
  );

  /// See [UserCategory.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<UserCategory>(
    _entities[4].properties[3],
  );

  /// see [UserCategory.entries]
  static final entries = obx.QueryRelationToMany<UserCategory, MediaFile>(
    _entities[4].relations[0],
  );
}
