name: Build and Release

on:
  push:
    tags:
      - '[0-9]{8}'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: 26100
          features: 'OptionId.UWPCPP,OptionId.DesktopCPParm64'

      - name: Install dependencies
        run: flutter pub get

      - name: Install dependencies libmpv_dart
        run: dart run libmpv_dart:setup --platform windows 

      - name: Build Windows release
        run: flutter build windows --release --verbose

      - name: Download FFmpeg
        run: Invoke-WebRequest -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z -OutFile ffmpeg-git-essentials.7z

      - name: Extract FFmpeg
        run: 7z x ffmpeg-git-essentials.7z -oFFmpeg_extracted ffmpeg-git-essentials/bin/ffmpeg.exe

      - name: Move FFmpeg to Release folder
        run: Move-Item -Path FFmpeg_extracted/ffmpeg-git-essentials/bin/ffmpeg.exe -Destination build/windows/runner/Release/ffmpeg.exe

      - name: Zip Release
        run: Compress-Archive -Path build/windows/runner/Release/* -DestinationPath syncopathy-windows-${{ github.ref_name }}.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: syncopathy-windows-${{ github.ref_name }}.zip

      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release of version ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./syncopathy-windows-${{ github.ref_name }}.zip
          asset_name: syncopathy-windows-${{ github.ref_name }}.zip
          asset_content_type: application/zip


