name: Build and Release

on:
  push:
    tags:
      - '[0-9]{8}'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install dependencies libmpv_dart
        run: dart run libmpv_dart:setup --platform windows 

      - name: Build Windows release
        run: flutter build windows --release

      - name: Download FFmpeg
        run: |
          Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z" -OutFile "ffmpeg.7z"
          7z x ffmpeg.7z -o"ffmpeg_extracted"
          Get-ChildItem -Path "ffmpeg_extracted" -Recurse -Filter "ffmpeg.exe" | Copy-Item -Destination "build/windows/x64/runner/Release/"

      - name: Zip Release
        run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath syncopathy-windows-${{ github.ref_name }}.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: syncopathy-windows-${{ github.ref_name }}.zip

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: syncopathy-windows-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


